[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc132"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc132-a = { alias = "a", problem = "https://atcoder.jp/contests/abc132/tasks/abc132_a" }
abc132-b = { alias = "b", problem = "https://atcoder.jp/contests/abc132/tasks/abc132_b" }
abc132-c = { alias = "c", problem = "https://atcoder.jp/contests/abc132/tasks/abc132_c" }
abc132-d = { alias = "d", problem = "https://atcoder.jp/contests/abc132/tasks/abc132_d" }
abc132-e = { alias = "e", problem = "https://atcoder.jp/contests/abc132/tasks/abc132_e" }
abc132-f = { alias = "f", problem = "https://atcoder.jp/contests/abc132/tasks/abc132_f" }

[[bin]]
name = "abc132-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc132-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc132-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc132-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc132-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc132-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
