[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "arc146"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
arc146-a = { alias = "a", problem = "https://atcoder.jp/contests/arc146/tasks/arc146_a" }
arc146-b = { alias = "b", problem = "https://atcoder.jp/contests/arc146/tasks/arc146_b" }
arc146-c = { alias = "c", problem = "https://atcoder.jp/contests/arc146/tasks/arc146_c" }
arc146-d = { alias = "d", problem = "https://atcoder.jp/contests/arc146/tasks/arc146_d" }
arc146-e = { alias = "e", problem = "https://atcoder.jp/contests/arc146/tasks/arc146_e" }
arc146-f = { alias = "f", problem = "https://atcoder.jp/contests/arc146/tasks/arc146_f" }

[[bin]]
name = "arc146-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc146-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc146-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc146-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc146-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc146-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
