[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc233"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc233-a = { alias = "a", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_a" }
abc233-b = { alias = "b", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_b" }
abc233-c = { alias = "c", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_c" }
abc233-d = { alias = "d", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_d" }
abc233-e = { alias = "e", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_e" }
abc233-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_h" }
abc233-f = { alias = "f", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_f" }
abc233-g = { alias = "g", problem = "https://atcoder.jp/contests/abc233/tasks/abc233_g" }

[[bin]]
name = "abc233-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc233-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc233-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc233-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc233-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc233-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc233-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc233-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
