[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "agc058"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
agc058-a = { alias = "a", problem = "https://atcoder.jp/contests/agc058/tasks/agc058_a" }
agc058-b = { alias = "b", problem = "https://atcoder.jp/contests/agc058/tasks/agc058_b" }
agc058-c = { alias = "c", problem = "https://atcoder.jp/contests/agc058/tasks/agc058_c" }
agc058-d = { alias = "d", problem = "https://atcoder.jp/contests/agc058/tasks/agc058_d" }
agc058-e = { alias = "e", problem = "https://atcoder.jp/contests/agc058/tasks/agc058_e" }
agc058-f = { alias = "f", problem = "https://atcoder.jp/contests/agc058/tasks/agc058_f" }

[[bin]]
name = "agc058-a"
path = "src/bin/a.rs"

[[bin]]
name = "agc058-b"
path = "src/bin/b.rs"

[[bin]]
name = "agc058-c"
path = "src/bin/c.rs"

[[bin]]
name = "agc058-d"
path = "src/bin/d.rs"

[[bin]]
name = "agc058-e"
path = "src/bin/e.rs"

[[bin]]
name = "agc058-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
