[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc165"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc165-a = { alias = "a", problem = "https://atcoder.jp/contests/abc165/tasks/abc165_a" }
abc165-b = { alias = "b", problem = "https://atcoder.jp/contests/abc165/tasks/abc165_b" }
abc165-c = { alias = "c", problem = "https://atcoder.jp/contests/abc165/tasks/abc165_c" }
abc165-d = { alias = "d", problem = "https://atcoder.jp/contests/abc165/tasks/abc165_d" }
abc165-e = { alias = "e", problem = "https://atcoder.jp/contests/abc165/tasks/abc165_e" }
abc165-f = { alias = "f", problem = "https://atcoder.jp/contests/abc165/tasks/abc165_f" }

[[bin]]
name = "abc165-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc165-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc165-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc165-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc165-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc165-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
