[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "sumitrust2019"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
sumitrust2019-a = { alias = "a", problem = "https://atcoder.jp/contests/sumitrust2019/tasks/sumitb2019_a" }
sumitrust2019-b = { alias = "b", problem = "https://atcoder.jp/contests/sumitrust2019/tasks/sumitb2019_b" }
sumitrust2019-c = { alias = "c", problem = "https://atcoder.jp/contests/sumitrust2019/tasks/sumitb2019_c" }
sumitrust2019-d = { alias = "d", problem = "https://atcoder.jp/contests/sumitrust2019/tasks/sumitb2019_d" }
sumitrust2019-e = { alias = "e", problem = "https://atcoder.jp/contests/sumitrust2019/tasks/sumitb2019_e" }
sumitrust2019-f = { alias = "f", problem = "https://atcoder.jp/contests/sumitrust2019/tasks/sumitb2019_f" }

[[bin]]
name = "sumitrust2019-a"
path = "src/bin/a.rs"

[[bin]]
name = "sumitrust2019-b"
path = "src/bin/b.rs"

[[bin]]
name = "sumitrust2019-c"
path = "src/bin/c.rs"

[[bin]]
name = "sumitrust2019-d"
path = "src/bin/d.rs"

[[bin]]
name = "sumitrust2019-e"
path = "src/bin/e.rs"

[[bin]]
name = "sumitrust2019-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
