[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc270"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc270-a = { alias = "a", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_a" }
abc270-b = { alias = "b", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_b" }
abc270-c = { alias = "c", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_c" }
abc270-d = { alias = "d", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_d" }
abc270-e = { alias = "e", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_e" }
abc270-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_h" }
abc270-f = { alias = "f", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_f" }
abc270-g = { alias = "g", problem = "https://atcoder.jp/contests/abc270/tasks/abc270_g" }

[[bin]]
name = "abc270-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc270-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc270-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc270-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc270-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc270-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc270-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc270-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
ndarray = "0.15.6"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
