[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc247"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc247-a = { alias = "a", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_a" }
abc247-b = { alias = "b", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_b" }
abc247-c = { alias = "c", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_c" }
abc247-d = { alias = "d", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_d" }
abc247-e = { alias = "e", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_e" }
abc247-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_h" }
abc247-f = { alias = "f", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_f" }
abc247-g = { alias = "g", problem = "https://atcoder.jp/contests/abc247/tasks/abc247_g" }

[[bin]]
name = "abc247-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc247-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc247-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc247-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc247-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc247-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc247-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc247-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
