[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "nikkei2019-qual"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-compete.bin]
nikkei2019-qual-a = { alias = "a", problem = "https://atcoder.jp/contests/nikkei2019-qual/tasks/nikkei2019_qual_a" }
nikkei2019-qual-b = { alias = "b", problem = "https://atcoder.jp/contests/nikkei2019-qual/tasks/nikkei2019_qual_b" }
nikkei2019-qual-c = { alias = "c", problem = "https://atcoder.jp/contests/nikkei2019-qual/tasks/nikkei2019_qual_c" }
nikkei2019-qual-d = { alias = "d", problem = "https://atcoder.jp/contests/nikkei2019-qual/tasks/nikkei2019_qual_d" }
nikkei2019-qual-e = { alias = "e", problem = "https://atcoder.jp/contests/nikkei2019-qual/tasks/nikkei2019_qual_e" }
nikkei2019-qual-f = { alias = "f", problem = "https://atcoder.jp/contests/nikkei2019-qual/tasks/nikkei2019_qual_f" }

[[bin]]
name = "nikkei2019-qual-a"
path = "src/bin/a.rs"

[[bin]]
name = "nikkei2019-qual-b"
path = "src/bin/b.rs"

[[bin]]
name = "nikkei2019-qual-c"
path = "src/bin/c.rs"

[[bin]]
name = "nikkei2019-qual-d"
path = "src/bin/d.rs"

[[bin]]
name = "nikkei2019-qual-e"
path = "src/bin/e.rs"

[[bin]]
name = "nikkei2019-qual-f"
path = "src/bin/f.rs"

[dependencies]
memoise="0.3.2"
counter="0.5.7"
hashbag="0.1.11"
pathfinding="4.2.1"
multimap="0.9.0"
btreemultimap="0.1.1"
num-bigint="0.4.3"
num-complex="0.4.3"
num-integer="0.1.45"
num-traits="0.2.15"
num-derive="0.3.3"
ndarray="0.15.6"
nalgebra="0.32.2"
rand="0.8.5"
petgraph="0.6.3"
indexmap="1.9.3"
regex="1.7.3"
lazy_static="1.4.0"
ordered-float="3.6.0"
itertools="0.10.5"
itertools-num="0.1.3"
permutohedron="0.2.4"
proconio="0.4.3"
text_io="0.1.12"

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
