[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "diverta2019-2"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
diverta2019-2-a = { alias = "a", problem = "https://atcoder.jp/contests/diverta2019-2/tasks/diverta2019_2_a" }
diverta2019-2-b = { alias = "b", problem = "https://atcoder.jp/contests/diverta2019-2/tasks/diverta2019_2_b" }
diverta2019-2-c = { alias = "c", problem = "https://atcoder.jp/contests/diverta2019-2/tasks/diverta2019_2_c" }
diverta2019-2-d = { alias = "d", problem = "https://atcoder.jp/contests/diverta2019-2/tasks/diverta2019_2_d" }
diverta2019-2-e = { alias = "e", problem = "https://atcoder.jp/contests/diverta2019-2/tasks/diverta2019_2_e" }
diverta2019-2-f = { alias = "f", problem = "https://atcoder.jp/contests/diverta2019-2/tasks/diverta2019_2_f" }

[[bin]]
name = "diverta2019-2-a"
path = "src/bin/a.rs"

[[bin]]
name = "diverta2019-2-b"
path = "src/bin/b.rs"

[[bin]]
name = "diverta2019-2-c"
path = "src/bin/c.rs"

[[bin]]
name = "diverta2019-2-d"
path = "src/bin/d.rs"

[[bin]]
name = "diverta2019-2-e"
path = "src/bin/e.rs"

[[bin]]
name = "diverta2019-2-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
