[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc208"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc208-a = { alias = "a", problem = "https://atcoder.jp/contests/abc208/tasks/abc208_a" }
abc208-b = { alias = "b", problem = "https://atcoder.jp/contests/abc208/tasks/abc208_b" }
abc208-c = { alias = "c", problem = "https://atcoder.jp/contests/abc208/tasks/abc208_c" }
abc208-d = { alias = "d", problem = "https://atcoder.jp/contests/abc208/tasks/abc208_d" }
abc208-e = { alias = "e", problem = "https://atcoder.jp/contests/abc208/tasks/abc208_e" }
abc208-f = { alias = "f", problem = "https://atcoder.jp/contests/abc208/tasks/abc208_f" }

[[bin]]
name = "abc208-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc208-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc208-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc208-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc208-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc208-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
