[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc235"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc235-a = { alias = "a", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_a" }
abc235-b = { alias = "b", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_b" }
abc235-c = { alias = "c", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_c" }
abc235-d = { alias = "d", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_d" }
abc235-e = { alias = "e", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_e" }
abc235-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_h" }
abc235-f = { alias = "f", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_f" }
abc235-g = { alias = "g", problem = "https://atcoder.jp/contests/abc235/tasks/abc235_g" }

[[bin]]
name = "abc235-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc235-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc235-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc235-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc235-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc235-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc235-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc235-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
