[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc198"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc198-a = { alias = "a", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_a" }
abc198-b = { alias = "b", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_b" }
abc198-c = { alias = "c", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_c" }
abc198-d = { alias = "d", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_d" }
abc198-e = { alias = "e", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_e" }
abc198-f = { alias = "f", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_f" }

[[bin]]
name = "abc198-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc198-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc198-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc198-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc198-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc198-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
