[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "agc057"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
agc057-a = { alias = "a", problem = "https://atcoder.jp/contests/agc057/tasks/agc057_a" }
agc057-b = { alias = "b", problem = "https://atcoder.jp/contests/agc057/tasks/agc057_b" }
agc057-c = { alias = "c", problem = "https://atcoder.jp/contests/agc057/tasks/agc057_c" }
agc057-d = { alias = "d", problem = "https://atcoder.jp/contests/agc057/tasks/agc057_d" }
agc057-e = { alias = "e", problem = "https://atcoder.jp/contests/agc057/tasks/agc057_e" }
agc057-f = { alias = "f", problem = "https://atcoder.jp/contests/agc057/tasks/agc057_f" }

[[bin]]
name = "agc057-a"
path = "src/bin/a.rs"

[[bin]]
name = "agc057-b"
path = "src/bin/b.rs"

[[bin]]
name = "agc057-c"
path = "src/bin/c.rs"

[[bin]]
name = "agc057-d"
path = "src/bin/d.rs"

[[bin]]
name = "agc057-e"
path = "src/bin/e.rs"

[[bin]]
name = "agc057-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
