[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc358"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-compete.bin]
abc358-a = { alias = "a", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_a" }
abc358-b = { alias = "b", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_b" }
abc358-c = { alias = "c", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_c" }
abc358-d = { alias = "d", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_d" }
abc358-e = { alias = "e", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_e" }
abc358-f = { alias = "f", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_f" }
abc358-g = { alias = "g", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_g" }

[[bin]]
name = "abc358-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc358-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc358-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc358-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc358-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc358-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc358-g"
path = "src/bin/g.rs"

[dependencies]
memoise="0.3.2"
counter="0.5.7"
hashbag="0.1.11"
pathfinding="4.2.1"
multimap="0.9.0"
btreemultimap="0.1.1"
num-bigint="0.4.3"
num-complex="0.4.3"
num-integer="0.1.45"
num-traits="0.2.15"
num-derive="0.3.3"
ndarray="0.15.6"
nalgebra="0.32.2"
rand="0.8.5"
petgraph="0.6.3"
indexmap="1.9.3"
regex="1.7.3"
lazy_static="1.4.0"
ordered-float="3.6.0"
itertools="0.10.5"
itertools-num="0.1.3"
permutohedron="0.2.4"
proconio="0.4.3"
text_io="0.1.12"

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
