[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "arc150"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
arc150-a = { alias = "a", problem = "https://atcoder.jp/contests/arc150/tasks/arc150_a" }
arc150-b = { alias = "b", problem = "https://atcoder.jp/contests/arc150/tasks/arc150_b" }
arc150-c = { alias = "c", problem = "https://atcoder.jp/contests/arc150/tasks/arc150_c" }
arc150-d = { alias = "d", problem = "https://atcoder.jp/contests/arc150/tasks/arc150_d" }
arc150-e = { alias = "e", problem = "https://atcoder.jp/contests/arc150/tasks/arc150_e" }
arc150-f = { alias = "f", problem = "https://atcoder.jp/contests/arc150/tasks/arc150_f" }

[[bin]]
name = "arc150-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc150-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc150-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc150-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc150-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc150-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
