[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "arc002"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
arc002-a = { alias = "a", problem = "https://atcoder.jp/contests/arc002/tasks/arc002_1" }
arc002-b = { alias = "b", problem = "https://atcoder.jp/contests/arc002/tasks/arc002_2" }
arc002-c = { alias = "c", problem = "https://atcoder.jp/contests/arc002/tasks/arc002_3" }
arc002-d = { alias = "d", problem = "https://atcoder.jp/contests/arc002/tasks/arc002_4" }

[[bin]]
name = "arc002-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc002-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc002-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc002-d"
path = "src/bin/d.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
ndarray = "0.15.6"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
