[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc259"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc259-a = { alias = "a", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_a" }
abc259-b = { alias = "b", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_b" }
abc259-c = { alias = "c", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_c" }
abc259-d = { alias = "d", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_d" }
abc259-e = { alias = "e", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_e" }
abc259-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_h" }
abc259-f = { alias = "f", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_f" }
abc259-g = { alias = "g", problem = "https://atcoder.jp/contests/abc259/tasks/abc259_g" }

[[bin]]
name = "abc259-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc259-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc259-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc259-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc259-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc259-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc259-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc259-g"
path = "src/bin/g.rs"

[dependencies]
memoise="0.3.2"
counter="0.5.7"
hashbag="0.1.11"
pathfinding="4.2.1"
multimap="0.9.0"
btreemultimap="0.1.1"
num-bigint="0.4.3"
num-complex="0.4.3"
num-integer="0.1.45"
num-traits="0.2.15"
num-derive="0.3.3"
ndarray="0.15.6"
nalgebra="0.32.2"
rand="0.8.5"
petgraph="0.6.3"
indexmap="1.9.3"
regex="1.7.3"
lazy_static="1.4.0"
ordered-float="3.6.0"
itertools="0.10.5"
itertools-num="0.1.3"
permutohedron="0.2.4"
proconio="0.4.3"
text_io="0.1.12"

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
