[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc126"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc126-a = { alias = "a", problem = "https://atcoder.jp/contests/abc126/tasks/abc126_a" }
abc126-b = { alias = "b", problem = "https://atcoder.jp/contests/abc126/tasks/abc126_b" }
abc126-c = { alias = "c", problem = "https://atcoder.jp/contests/abc126/tasks/abc126_c" }
abc126-d = { alias = "d", problem = "https://atcoder.jp/contests/abc126/tasks/abc126_d" }
abc126-e = { alias = "e", problem = "https://atcoder.jp/contests/abc126/tasks/abc126_e" }
abc126-f = { alias = "f", problem = "https://atcoder.jp/contests/abc126/tasks/abc126_f" }

[[bin]]
name = "abc126-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc126-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc126-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc126-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc126-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc126-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
ndarray = "0.15.6"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
