[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "arc145"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
arc145-a = { alias = "a", problem = "https://atcoder.jp/contests/arc145/tasks/arc145_a" }
arc145-b = { alias = "b", problem = "https://atcoder.jp/contests/arc145/tasks/arc145_b" }
arc145-c = { alias = "c", problem = "https://atcoder.jp/contests/arc145/tasks/arc145_c" }
arc145-d = { alias = "d", problem = "https://atcoder.jp/contests/arc145/tasks/arc145_d" }
arc145-e = { alias = "e", problem = "https://atcoder.jp/contests/arc145/tasks/arc145_e" }
arc145-f = { alias = "f", problem = "https://atcoder.jp/contests/arc145/tasks/arc145_f" }

[[bin]]
name = "arc145-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc145-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc145-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc145-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc145-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc145-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
