[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "arc142"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
arc142-a = { alias = "a", problem = "https://atcoder.jp/contests/arc142/tasks/arc142_a" }
arc142-b = { alias = "b", problem = "https://atcoder.jp/contests/arc142/tasks/arc142_b" }
arc142-c = { alias = "c", problem = "https://atcoder.jp/contests/arc142/tasks/arc142_c" }
arc142-d = { alias = "d", problem = "https://atcoder.jp/contests/arc142/tasks/arc142_d" }
arc142-e = { alias = "e", problem = "https://atcoder.jp/contests/arc142/tasks/arc142_e" }
arc142-f = { alias = "f", problem = "https://atcoder.jp/contests/arc142/tasks/arc142_f" }

[[bin]]
name = "arc142-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc142-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc142-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc142-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc142-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc142-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
