[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc194"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc194-a = { alias = "a", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_a" }
abc194-b = { alias = "b", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_b" }
abc194-c = { alias = "c", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_c" }
abc194-d = { alias = "d", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_d" }
abc194-e = { alias = "e", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_e" }
abc194-f = { alias = "f", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_f" }

[[bin]]
name = "abc194-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc194-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc194-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc194-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc194-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc194-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
