[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc167"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc167-a = { alias = "a", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_a" }
abc167-b = { alias = "b", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_b" }
abc167-c = { alias = "c", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_c" }
abc167-d = { alias = "d", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_d" }
abc167-e = { alias = "e", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_e" }
abc167-f = { alias = "f", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_f" }

[[bin]]
name = "abc167-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc167-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc167-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc167-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc167-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc167-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
