[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc242"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc242-a = { alias = "a", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_a" }
abc242-b = { alias = "b", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_b" }
abc242-c = { alias = "c", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_c" }
abc242-d = { alias = "d", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_d" }
abc242-e = { alias = "e", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_e" }
abc242-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_h" }
abc242-f = { alias = "f", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_f" }
abc242-g = { alias = "g", problem = "https://atcoder.jp/contests/abc242/tasks/abc242_g" }

[[bin]]
name = "abc242-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc242-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc242-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc242-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc242-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc242-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc242-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc242-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
