[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "abc189"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc189-a = { alias = "a", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_a" }
abc189-b = { alias = "b", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_b" }
abc189-c = { alias = "c", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_c" }
abc189-d = { alias = "d", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_d" }
abc189-e = { alias = "e", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_e" }
abc189-f = { alias = "f", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_f" }

[[bin]]
name = "abc189-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc189-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc189-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc189-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc189-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc189-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
ndarray = "0.15.6"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
