[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "arc148"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
arc148-a = { alias = "a", problem = "https://atcoder.jp/contests/arc148/tasks/arc148_a" }
arc148-b = { alias = "b", problem = "https://atcoder.jp/contests/arc148/tasks/arc148_b" }
arc148-c = { alias = "c", problem = "https://atcoder.jp/contests/arc148/tasks/arc148_c" }
arc148-d = { alias = "d", problem = "https://atcoder.jp/contests/arc148/tasks/arc148_d" }
arc148-e = { alias = "e", problem = "https://atcoder.jp/contests/arc148/tasks/arc148_e" }
arc148-f = { alias = "f", problem = "https://atcoder.jp/contests/arc148/tasks/arc148_f" }

[[bin]]
name = "arc148-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc148-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc148-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc148-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc148-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc148-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
