[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "tenka1-2018"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
tenka1-2018-c = { alias = "c", problem = "https://atcoder.jp/contests/tenka1-2018/tasks/tenka1_2018_c" }
tenka1-2018-d = { alias = "d", problem = "https://atcoder.jp/contests/tenka1-2018/tasks/tenka1_2018_d" }
tenka1-2018-e = { alias = "e", problem = "https://atcoder.jp/contests/tenka1-2018/tasks/tenka1_2018_e" }
tenka1-2018-f = { alias = "f", problem = "https://atcoder.jp/contests/tenka1-2018/tasks/tenka1_2018_f" }

[[bin]]
name = "tenka1-2018-c"
path = "src/bin/c.rs"

[[bin]]
name = "tenka1-2018-d"
path = "src/bin/d.rs"

[[bin]]
name = "tenka1-2018-e"
path = "src/bin/e.rs"

[[bin]]
name = "tenka1-2018-f"
path = "src/bin/f.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
