[profile.dev]
opt-level = 3

[profile.release]
strip = true

[package]
name = "caddi2018b"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
caddi2018b-a = { alias = "a", problem = "https://atcoder.jp/contests/caddi2018b/tasks/caddi2018b_a" }
caddi2018b-b = { alias = "b", problem = "https://atcoder.jp/contests/caddi2018b/tasks/caddi2018b_b" }
caddi2018b-c = { alias = "c", problem = "https://atcoder.jp/contests/caddi2018b/tasks/caddi2018_a" }
caddi2018b-d = { alias = "d", problem = "https://atcoder.jp/contests/caddi2018b/tasks/caddi2018_b" }

[[bin]]
name = "caddi2018b-a"
path = "src/bin/a.rs"

[[bin]]
name = "caddi2018b-b"
path = "src/bin/b.rs"

[[bin]]
name = "caddi2018b-c"
path = "src/bin/c.rs"

[[bin]]
name = "caddi2018b-d"
path = "src/bin/d.rs"

[dependencies]
itertools = "0.10.3"
itertools-num = "0.1.3"
num-integer = "0.1.45"
num-complex = "0.4.2"
num-bigint = "0.4.3"
petgraph = "0.6.2"
proconio = { version = "0.3.7", features = ["derive"] }

ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }

[dev-dependencies]
